name: Build and Deploy documentation
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: get build deps
        run: |
          sudo apt install pandoc
          pip install -r doc-requirements.txt

      - name: build docs
        run: |
          pip install .
          cd docs
          make html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
